wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708827067.60147
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      3:
      - 23
      4: 3.12.2
      5: 0.16.3
      6: 4.38.1
      8:
      - 5
      13: linux-x86_64
input_perturbation:
  desc: null
  value: 0
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
revision:
  desc: null
  value: null
variant:
  desc: null
  value: null
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
train_data_dir:
  desc: null
  value: data/kanji_images
image_column:
  desc: null
  value: image
caption_column:
  desc: null
  value: text
max_train_samples:
  desc: null
  value: null
output_dir:
  desc: null
  value: /lab/tmpig7b/u/yxiao-data/sd_kanji
cache_dir:
  desc: null
  value: null
seed:
  desc: null
  value: null
resolution:
  desc: null
  value: 512
center_crop:
  desc: null
  value: true
random_flip:
  desc: null
  value: true
train_batch_size:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 41
max_train_steps:
  desc: null
  value: 15000
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0001
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
snr_gamma:
  desc: null
  value: null
use_8bit_adam:
  desc: null
  value: false
allow_tf32:
  desc: null
  value: false
use_ema:
  desc: null
  value: true
non_ema_revision:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: true
hub_token:
  desc: null
  value: null
prediction_type:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
logging_dir:
  desc: null
  value: logs
mixed_precision:
  desc: null
  value: fp16
report_to:
  desc: null
  value: wandb
local_rank:
  desc: null
  value: -1
checkpointing_steps:
  desc: null
  value: 5000
checkpoints_total_limit:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
enable_xformers_memory_efficient_attention:
  desc: null
  value: false
noise_offset:
  desc: null
  value: 0
validation_epochs:
  desc: null
  value: 5
tracker_project_name:
  desc: null
  value: sd_kanji
